spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:poc;DB_CLOSE_ON_EXIT=FALSE;Mode=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS SCORE_BOARD
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
  data:
    rest:
      default-media-type: application/json
      default-page-size: 10
      base-path: v1/

---
spring:
  config:
    activate:
      on-profile: pgSql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:3001/digilink_dev_db
    driver-class-name: org.postgresql.Driver
    password: Merc4503b
    username: dev_user
  h2:
    console:
      path: /h2-console
  data:
    rest:
      default-media-type: application/json
      default-page-size: 10
      base-path: v1/
