INSERT INTO SCORE_BOARD.SCORE ( DESCRIPTION)
VALUES (N'Great');
INSERT INTO SCORE_BOARD.SCORE ( DESCRIPTION)
VALUES (N'good');
INSERT INTO SCORE_BOARD.SCORE ( DESCRIPTION)
VALUES (N'Average');
INSERT INTO SCORE_BOARD.SCORE ( DESCRIPTION)
VALUES (N'needs work');
INSERT INTO SCORE_BOARD.SCORE ( DESCRIPTION)
VALUES (N'poor');



INSERT INTO SCORE_BOARD.CATEGORY (NAME, DESCRIPTION)
VALUES (N'Soft Desc', N'Soft');
INSERT INTO SCORE_BOARD.CATEGORY (NAME, DESCRIPTION)
VALUES (N'Tech Desc', N'Tech');
INSERT INTO SCORE_BOARD.CATEGORY (NAME, DESCRIPTION)
VALUES (N'Tech Desc', N'Tech client');

-- SELECT * FROM "SCORE_BOARD"."SUB_CATEGORY";



INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Soft skill three', 1);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Soft skill one', 1);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Soft skill two', 1);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech skill three', 2);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech skill one', 2);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech skill two', 2);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech client two', 3);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech client three', 3);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (NAME, DESCRIPTION, CATEGORY_ID)
VALUES (N'score', N'Tech client one', 3);