INSERT INTO SCORE_BOARD.SCORE (ID, RATING, DESCRIPTION)
VALUES (1, 5, N'Great');
INSERT INTO SCORE_BOARD.SCORE (ID, RATING, DESCRIPTION)
VALUES (2, 4, N'good');
INSERT INTO SCORE_BOARD.SCORE (ID, RATING, DESCRIPTION)
VALUES (3, 3, N'Average');
INSERT INTO SCORE_BOARD.SCORE (ID, RATING, DESCRIPTION)
VALUES (4, 2, N'needs work');
INSERT INTO SCORE_BOARD.SCORE (ID, RATING, DESCRIPTION)
VALUES (5, 1, N'poor');



INSERT INTO SCORE_BOARD.CATEGORY (ID, NAME, DESCRIPTION)
VALUES (1, N'Soft Desc', N'Soft');
INSERT INTO SCORE_BOARD.CATEGORY (ID, NAME, DESCRIPTION)
VALUES (2, N'Tech Desc', N'Tech');
INSERT INTO SCORE_BOARD.CATEGORY (ID, NAME, DESCRIPTION)
VALUES (3, N'Tech Desc', N'Tech client');

-- SELECT * FROM "SCORE_BOARD"."SUB_CATEGORY";


//SUBCATEGORY
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (1, N'score', N'Soft skill three', 1, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (2, N'score', N'Soft skill one', 1, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (3, N'score', N'Soft skill two', 1, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (4, N'score', N'Tech skill three', 2, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (5, N'score', N'Tech skill one', 2, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (6, N'score', N'Tech skill two', 2, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (7, N'score', N'Tech client two', 3, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (8, N'score', N'Tech client three', 3, null);
INSERT INTO SCORE_BOARD.SUB_CATEGORY (ID, NAME, DESCRIPTION, CATEGORYID, SCOREID)
VALUES (9, N'score', N'Tech client one', 3, null);