SELECT *FROM Candidate_PROD.dbo.candidates;

-- INSERT INTO dev_db.Candidate.CANDIDATE(PHONE_NUMBER, ID_NUMBER, START_DATE, PLACEMENT_DATE, END_DATE, LAST_UPDATED, APP_USERID, QUALIFICATIONID, COMPANYID, COHORTID, STATUSID;
-- SELECT phone, id_number, start_date,  FROM Candidate_PROD.dbo.candidates
